FROM forecasting-base:latest

WORKDIR /app

COPY forecasting_engine/ ./forecasting_engine/

EXPOSE 5050

RUN mkdir -p /mlflow/artifacts

CMD mlflow server \
    --backend-store-uri "$MLFLOW_DB_URI_STAGING" \
    --default-artifact-root "$MLFLOW_S3_BUCKET_URI_STAGING" \
    --host 0.0.0.0 \
    --port 5050