FROM forecasting-base:latest

WORKDIR /app

COPY forecasting_engine/ ./forecasting_engine/

EXPOSE 5050

CMD mlflow server \
    --backend-store-uri "$MLFLOW_DB_URI" \
    --default-artifact-root "$MLFLOW_ARTIFACT_ROOT" \
    --host 0.0.0.0 \
    --port 5050