FROM forecasting-base:latest

WORKDIR /app

COPY forecasting_engine ./forecasting_engine

# mlflow Dockerfile:
CMD mlflow server \
    --backend-store-uri "$MLFLOW_DB_URI" \
    --default-artifact-root "$MLFLOW_ARTIFACT_ROOT" \
    --host 0.0.0.0 \
    --port 5050

# forecasting Dockerfile (no CMD):
# just run scripts explicitly in your container commands