version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: forecasting-base:latest
  mlflow:
    image: forecasting-base:latest
    container_name: mlflow
    env_file:
      - .env
    ports:
      - "5050:5050"
    command: >
      mlflow server
      --backend-store-uri "$MLFLOW_DB_URI"
      --default-artifact-root "$MLFLOW_ARTIFACT_ROOT"
      --host 0.0.0.0
      --port 5050
      --workers 1

  forecasting:  # Just a dev container
    image: forecasting-base:latest
    container_name: forecasting-tasks
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: tail -f /dev/null  

  forecast-poller:
    image: forecasting-base:latest
    container_name: forecast-poller
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: python -m forecasting_engine.services.forecast_poller.main


  forecast-enqueuer:
    image: forecasting-base:latest
    container_name: forecast-enqueuer
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: python -m forecasting_engine.services.forecast_enqueuer.main

  cleanup:  # Calls a cleanup script every day to delete old temp files
    image: forecasting-base:latest
    container_name: cleanup
    command: >
      sh -c "while true; do
               /usr/local/bin/cleanup.sh
               sleep 86400
             done"
