FROM forecasting-base:latest

WORKDIR /app

# Shared env vars for Python behavior
ENV PYTHONPATH=/app \
    PYTHONDONTWRITEBYTECODE=1

# Copy source
COPY forecasting_engine ./forecasting_engine

# Port is only relevant for mlflow server
EXPOSE 5050