FROM forecasting-base:latest

WORKDIR /app

# Set python path so docker commands can run scripts
ENV PYTHONPATH=/app

# Prevent .pyc files from being written to your source directory:
ENV PYTHONDONTWRITEBYTECODE=1

COPY forecasting_engine ./forecasting_engine

# mlflow Dockerfile:
CMD mlflow server \
    --backend-store-uri "$MLFLOW_DB_URI" \
    --default-artifact-root "$MLFLOW_ARTIFACT_ROOT" \
    --host 0.0.0.0 \
    --port 5050
