version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: forecasting-base:latest
  mlflow:
    image: forecasting-base:latest
    container_name: mlflow
    env_file:
      - .env
    ports:
      - "5050:5050"
    command: >
      mlflow server
      --backend-store-uri "$MLFLOW_DB_URI"
      --default-artifact-root "$MLFLOW_ARTIFACT_ROOT"
      --host 0.0.0.0
      --port 5050
      --workers 1

  forecasting:  # Just a dev container
    image: forecasting-base:latest
    container_name: forecasting-tasks
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: tail -f /dev/null  

  forecast-poller:
    image: forecasting-base:latest
    container_name: forecast-poller
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: python -m forecasting_engine.services.forecast_poller.main


  forecast-enqueuer:
    image: forecasting-base:latest
    container_name: forecast-enqueuer
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: python -m forecasting_engine.services.forecast_enqueuer.main

  model-trainer: # Service that trains the models every Sunday at 1am UTC (8pm EST)
    image: forecasting-base:latest
    container_name: model-trainer
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: >
      sh -c "echo '0 1 * * 0 python -m forecasting_engine.services.model_trainer.main' > /crontab &&
             supercronic /crontab"

  cleanup:  # Service that cleans up old logs and containers once per day
    image: forecasting-base:latest
    container_name: cleanup
    env_file:
      - .env
    volumes:
      - ./forecasting_engine:/app/forecasting_engine
    working_dir: /app
    command: >
      sh -c "echo '0 0 * * * /usr/local/bin/cleanup.sh' > /crontab &&
             supercronic /crontab"