# SPDX-FileCopyrightText: 2017-2024 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0

# Copied from https://github.com/rickstaa/action-black

# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action
# does nothing. Otherwise, Black is run and its changes are suggested in the
# incoming pull request. See 
# https://github.com/rickstaa/action-black?tab=readme-ov-file#annotate-changes 
# for a similar example.

name: Black Format Code

on:
  push:
    branches:
      - '**'        # Run on any push to any branch
  pull_request:  # Trigger on PRs to main
    types: [opened, synchronize, reopened]  # Trigger on PR events

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']

    permissions:
      pull-requests: write  # Ensure reviewdog can annotate the PR

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}  # Ensure this token is set correctly

      - name: Check formatting using black
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Debug PR and Repository Info
        run: |
          echo "PR Info: ${{ github.event.pull_request.title }}"
          echo "Repository Info: ${{ github.repository }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Make sure this token has correct scopes
