name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install minimal dependencies and generate .rst files
        run: |
          pip install sphinx-autodoc-typehints
          sphinx-apidoc -o forecasting_engine/openstef/docs forecasting_engine/openstef

      - name: Build and commit Sphinx docs to GitHub Pages
        uses: sphinx-notes/pages@v2
        with:
          docs_dir: forecasting_engine/openstef/docs

      - name: Push changes to gh-pages branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
