# SPDX-FileCopyrightText: 2017-2023 Contributors to the OpenSTEF project <korte.termijn.prognoses@alliander.com> # noqa E501
#
# SPDX-License-Identifier: MPL-2.0
name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and generate .rst files
        run: |
          cp requirements.txt forecasting_engine/openstef/docs/requirements.txt
          printf "\npydata-sphinx-theme==0.12.0\n" >> forecasting_engine/openstef/docs/requirements.txt
          printf "\njinja2==3.0.0\n" >> forecasting_engine/openstef/docs/requirements.txt
          printf "\nsphinx_autodoc_typehints==1.19.4\n" >> forecasting_engine/openstef/docs/requirements.txt
          printf "\nmkdocs==1.2.3\n" >> forecasting_engine/openstef/docs/requirements.txt
          pip install -r forecasting_engine/openstef/docs/requirements.txt
          sphinx-apidoc -o forecasting_engine/openstef/docs forecasting_engine/openstef

      - name: Build and commit Sphinx docs to GitHub Pages
        uses: sphinx-notes/pages@v2
        with:
          docs_dir: forecasting_engine/openstef/docs
          requirements_path: forecasting_engine/openstef/docs/requirements.txt

      - name: Push changes to gh-pages branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
