name: Test and Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    # Checkout
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    
    - name: Check formatting using black
      uses: rickstaa/action-black@v1
      id: action_black
      with:
        black_args: "."  # Arguments to pass to black

    - name: Lint
      run: |
        pip install flake8
        # Stop build on a couple more serious violations
        # See https://flake8.pycqa.org/en/latest/user/error-codes.html for more details
        flake8 . --count --select=E9,F63,F7,F8 --show-source --statistics
        # Only print warnings on all other errors
        flake8 . --count --exit-zero --show-source --statistics

    - name: Unit test with pytest
      run: |
        pip install -r test-requirements.txt
        pytest --cov=forecasting_engine/ --cov-branch --cov-report=xml:coverage.xml --cov-report=term-missing test/ --junitxml=pytest-report.xml

    - name: Combine coverage data files
      run: |
        pip install coverage
        coverage combine
    
    - name: Upload coverage data file
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: ./.coverage
        retention-days: 14
  
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
        retention-days: 14

  coverage:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
    - name: Download coverage data
      uses: actions/download-artifact@v4
      with:
        name: coverage-data
    
    - name: Move .coverage to working dir
      run: mv coverage-data/.coverage ./

    - name: Display coverage summary
      run: |
        pip install coverage
        coverage report --fail-under=85