name: Test and Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test and Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Login to AWS CodeArtifact
      id: login
      run: |
        echo "${{ secrets.ENV_FILE_STAGING }}" > .env
        set -a
        source .env
        set +a

        # Make AWS vars available for next steps
        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
        echo "AWS_REGION=$AWS_REGION" >> $GITHUB_ENV

        TOKEN=$(aws codeartifact get-authorization-token \
          --domain skyblu \
          --domain-owner 591082451778 \
          --region $AWS_REGION \
          --query authorizationToken \
          --output text)

        echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

    - name: Set DATABASE_URL for CI
      run: echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/appdb" >> $GITHUB_ENV

    - name: Install forecasting-engine package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r test-requirements.txt
        pip install --no-cache-dir \
            --index-url https://aws:${CODEARTIFACT_AUTH_TOKEN}@skyblu-591082451778.d.codeartifact.${AWS_REGION}.amazonaws.com/pypi/forecasting-db/simple/ \
            --extra-index-url https://pypi.org/simple \
            -r requirements.txt
        pip install --no-cache-dir flake8 coverage pytest
        pip install -e .

    - name: Check formatting using black
      uses: rickstaa/action-black@v1
      with:
        black_args: "."

    - name: Lint with Flake8 (Black-compatible)
      run: |
        flake8 . --count --ignore=E203,W503,E501,E701,C901,W504,E704 --show-source --statistics

    - name: Run tests with coverage
      run: |
        export PYTHONPATH=${{ github.workspace }}
        coverage run --source=forecasting_engine -m pytest test/
        coverage report -m
        coverage xml
      
    - name: Fix coverage paths for CI
      run: |
        sed -i 's|/home/runner/work/forecasting-engine/forecasting-engine/|/github/workspace/|g' coverage.xml

    - name: Check final coverage summary
      run: |
        coverage report --show-missing

    - name: Display coverage summary
      run: coverage report --fail-under=87 --ignore-errors

    - name: Upload coverage.xml
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
        retention-days: 14
