name: Test and Coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }}
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Check formatting using black
      uses: rickstaa/action-black@v1
      id: action_black
      with:
        black_args: "."

    - name: Lint
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F8 --show-source --statistics
        flake8 . --count --exit-zero --show-source --statistics

    - name: Unit test with pytest
      run: |
        pip install -r test-requirements.txt
        pytest --cov --cov-config=.coveragerc \
          --cov-report=xml:coverage.xml \
          --cov-report=term-missing \
          test/ --junitxml=pytest-report.xml

    - name: Combine coverage data files
      run: |
        pip install coverage
        coverage combine

    - name: Save coverage artifacts
      run: |
        mkdir -p coverage-artifacts
        mv .coverage coverage-artifacts/

    - name: Upload .coverage data
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: coverage-artifacts/
        retention-days: 14
        include-hidden-files: true

    - name: Upload coverage.xml
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.xml
        retention-days: 14

  coverage:
    name: Report Coverage
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Download .coverage file
      uses: actions/download-artifact@v4
      with:
        name: coverage-data

    - name: List contents of downloaded coverage-data
      run: |
        echo "Listing:"
        find coverage-data

    - name: Move .coverage file to root
      run: |
        mv coverage-data/coverage-artifacts/.coverage .

    - name: Install source for coverage resolution
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .

    - name: Generate coverage summary
      run: |
        pip install coverage
        coverage report --fail-under=85 --ignore-errors
